package org.example.random_data_generater.bean.date_time;

import java.io.Serializable;

public enum GlobalTimeFormat implements Serializable {

    //12:30:20
    TIME_FORMAT_1("hh:mm:ss"),
    TIME_FORMAT_2("hh:ss:mm"),
    TIME_FORMAT_3("mm:hh:ss"),
    TIME_FORMAT_4("mm:ss:hh"),
    TIME_FORMAT_5("ss:hh:mm"),
    TIME_FORMAT_6("ss:mm:hh"),
    TIME_FORMAT_7("hhmmss"),
    TIME_FORMAT_8("hhssmm"),
    TIME_FORMAT_9("mmhhss"),
    TIME_FORMAT_10("mmsshh"),
    TIME_FORMAT_11("sshhmm"),
    TIME_FORMAT_12("ssmmhh"),
    TIME_FORMAT_13("hh mm ss"),
    TIME_FORMAT_14("hh ss mm"),
    TIME_FORMAT_15("mm hh ss"),
    TIME_FORMAT_16("mm ss hh"),
    TIME_FORMAT_17("ss hh mm"),
    TIME_FORMAT_18("ss mm hh"),
    //12:30:20am
    TIME_FORMAT_19("hh:mm:ssa"),
    TIME_FORMAT_20("hh:ssa:mm"),
    TIME_FORMAT_21("mm:hh:ssa"),
    TIME_FORMAT_22("mm:ssa:hh"),
    TIME_FORMAT_23("ssa:hh:mm"),
    TIME_FORMAT_24("ssa:mm:hh"),
    TIME_FORMAT_25("hhmmssa"),
    TIME_FORMAT_26("hhssamm"),
    TIME_FORMAT_27("mmhhssa"),
    TIME_FORMAT_28("mmssahh"),
    TIME_FORMAT_29("ssahhmm"),
    TIME_FORMAT_30("ssammhh"),
    TIME_FORMAT_31("hh mm ssa"),
    TIME_FORMAT_32("hh ssa mm"),
    TIME_FORMAT_33("mm hh ssa"),
    TIME_FORMAT_34("mm ssa hh"),
    TIME_FORMAT_35("ssa hh mm"),
    TIME_FORMAT_36("ssa mm hh"),
    //12:30:20 am
    TIME_FORMAT_37("hh:mm:ss a"),
    TIME_FORMAT_38("hh:ss a:mm"),
    TIME_FORMAT_39("mm:hh:ss a"),
    TIME_FORMAT_40("mm:ss a:hh"),
    TIME_FORMAT_41("ss a:hh:mm"),
    TIME_FORMAT_42("ss a:mm:hh"),
    TIME_FORMAT_43("hhmmss a"),
    TIME_FORMAT_44("hhss amm"),
    TIME_FORMAT_45("mmhhss a"),
    TIME_FORMAT_46("mmss ahh"),
    TIME_FORMAT_47("ss ahhmm"),
    TIME_FORMAT_48("ss ammhh"),
    TIME_FORMAT_49("hh mm ss a"),
    TIME_FORMAT_50("hh ss a mm"),
    TIME_FORMAT_51("mm hh ss a"),
    TIME_FORMAT_52("mm ss a hh"),
    TIME_FORMAT_53("ss a hh mm"),
    TIME_FORMAT_54("ss a mm hh"),
    //12:30:20.234 am
    TIME_FORMAT_55("hh:mm:ss.SSS a"),
    TIME_FORMAT_56("hh:ss.SSS a:mm"),
    TIME_FORMAT_57("mm:hh:ss.SSS a"),
    TIME_FORMAT_58("mm:ss.SSS a:hh"),
    TIME_FORMAT_59("ss.SSS a:hh:mm"),
    TIME_FORMAT_60("ss.SSS a:mm:hh"),
    TIME_FORMAT_61("hhmmss.SSS a"),
    TIME_FORMAT_62("hhss.SSS amm"),
    TIME_FORMAT_63("mmhhss.SSS a"),
    TIME_FORMAT_64("mmss.SSS ahh"),
    TIME_FORMAT_65("ss.SSS ahhmm"),
    TIME_FORMAT_66("ss.SSS ammhh"),
    TIME_FORMAT_67("hh mm ss.SSS a"),
    TIME_FORMAT_68("hh ss.SSS a mm"),
    TIME_FORMAT_69("mm hh ss.SSS a"),
    TIME_FORMAT_70("mm ss.SSS a hh"),
    TIME_FORMAT_71("ss.SSS a hh mm"),
    TIME_FORMAT_72("ss.SSS a mm hh"),
    //12:30:20.234am
    TIME_FORMAT_73("hh:mm:ss.SSSa"),
    TIME_FORMAT_74("hh:ss.SSSa:mm"),
    TIME_FORMAT_75("mm:hh:ss.SSSa"),
    TIME_FORMAT_76("mm:ss.SSSa:hh"),
    TIME_FORMAT_77("ss.SSSa:hh:mm"),
    TIME_FORMAT_78("ss.SSSa:mm:hh"),
    TIME_FORMAT_79("hhmmss.SSSa"),
    TIME_FORMAT_80("hhss.SSSamm"),
    TIME_FORMAT_81("mmhhss.SSSa"),
    TIME_FORMAT_82("mmss.SSSahh"),
    TIME_FORMAT_83("ss.SSSahhmm"),
    TIME_FORMAT_84("ss.SSSammhh"),
    TIME_FORMAT_85("hh mm ss.SSSa"),
    TIME_FORMAT_86("hh ss.SSSa mm"),
    TIME_FORMAT_87("mm hh ss.SSSa"),
    TIME_FORMAT_88("mm ss.SSSa hh"),
    TIME_FORMAT_89("ss.SSSa hh mm"),
    TIME_FORMAT_90("ss.SSSa mm hh"),
    //15:30:20.234
    TIME_FORMAT_91("HH:mm:ss.SSS"),
    TIME_FORMAT_92("HH:ss.SSS:mm"),
    TIME_FORMAT_93("mm:HH:ss.SSS"),
    TIME_FORMAT_94("mm:ss.SSS:HH"),
    TIME_FORMAT_95("ss.SSS:HH:mm"),
    TIME_FORMAT_96("ss.SSS:mm:HH"),
    TIME_FORMAT_97("HHmmss.SSS"),
    TIME_FORMAT_98("HHss.SSSmm"),
    TIME_FORMAT_99("mmHHss.SSS"),
    TIME_FORMAT_100("mmss.SSSHH"),
    TIME_FORMAT_101("ss.SSSHHmm"),
    TIME_FORMAT_102("ss.SSSmmHH"),
    TIME_FORMAT_103("HH mm ss.SSS"),
    TIME_FORMAT_104("HH ss.SSS mm"),
    TIME_FORMAT_105("mm HH ss.SSS"),
    TIME_FORMAT_106("mm ss.SSS HH"),
    TIME_FORMAT_107("ss.SSS HH mm"),
    TIME_FORMAT_108("ss.SSS mm HH"),
//15:30:20.234 am
    TIME_FORMAT_109("HH:mm:ss.SSS a"),
    TIME_FORMAT_110("HH:ss.SSS a:mm"),
    TIME_FORMAT_111("mm:HH:ss.SSS a"),
    TIME_FORMAT_112("mm:ss.SSS a:HH"),
    TIME_FORMAT_113("ss.SSS a:HH:mm"),
    TIME_FORMAT_114("ss.SSS a:mm:HH"),
    TIME_FORMAT_115("HHmmss.SSS a"),
    TIME_FORMAT_116("HHss.SSS amm"),
    TIME_FORMAT_117("mmHHss.SSS a"),
    TIME_FORMAT_118("mmss.SSS aHH"),
    TIME_FORMAT_119("ss.SSS aHHmm"),
    TIME_FORMAT_120("ss.SSS ammHH"),
    TIME_FORMAT_121("HH mm ss.SSS a"),
    TIME_FORMAT_122("HH ss.SSS a mm"),
    TIME_FORMAT_123("mm HH ss.SSS a"),
    TIME_FORMAT_124("mm ss.SSS a HH"),
    TIME_FORMAT_125("ss.SSS a HH mm"),
    TIME_FORMAT_126("ss.SSS a mm HH"),
    //15:30:20 am
    TIME_FORMAT_127("HH:mm:ss a"),
    TIME_FORMAT_128("HH:ss a:mm"),
    TIME_FORMAT_129("mm:HH:ss a"),
    TIME_FORMAT_130("mm:ss a:HH"),
    TIME_FORMAT_131("ss a:HH:mm"),
    TIME_FORMAT_132("ss a:mm:HH"),
    TIME_FORMAT_133("HHmmss a"),
    TIME_FORMAT_134("HHss amm"),
    TIME_FORMAT_135("mmHHss a"),
    TIME_FORMAT_136("mmss aHH"),
    TIME_FORMAT_137("ss aHHmm"),
    TIME_FORMAT_138("ss ammHH"),
    TIME_FORMAT_139("HH mm ss a"),
    TIME_FORMAT_140("HH ss a mm"),
    TIME_FORMAT_141("mm HH ss a"),
    TIME_FORMAT_142("mm ss a HH"),
    TIME_FORMAT_143("ss a HH mm"),
    TIME_FORMAT_144("ss a mm HH"),
    //15:30:20am
    TIME_FORMAT_145("HH:mm:ssa"),
    TIME_FORMAT_146("H  H:ssa:mm"),
    TIME_FORMAT_147("mm:HH:ssa"),
    TIME_FORMAT_148("mm:ssa:HH"),
    TIME_FORMAT_149("ssa:HH:mm"),
    TIME_FORMAT_150("ssa:mm:HH"),
    TIME_FORMAT_151("HHmmssa"),
    TIME_FORMAT_152("HHssamm"),
    TIME_FORMAT_153("mmHHssa"),
    TIME_FORMAT_154("mmssaHH"),
    TIME_FORMAT_155("ssaHHmm"),
    TIME_FORMAT_156("ssammHH"),
    TIME_FORMAT_157("HH mm ssa"),
    TIME_FORMAT_158("HH ssa mm"),
    TIME_FORMAT_159("mm HH ssa"),
    TIME_FORMAT_160("mm ssa HH"),
    TIME_FORMAT_161("ssa HH mm"),
    TIME_FORMAT_162("ssa mm HH"),
    //15:30:20
    TIME_FORMAT_163("HH:mm:ss"),
    TIME_FORMAT_164("HH:ss:mm"),
    TIME_FORMAT_165("mm:HH:ss"),
    TIME_FORMAT_166("mm:ss:HH"),
    TIME_FORMAT_167("ss:HH:mm"),
    TIME_FORMAT_168("ss:mm:HH"),
    TIME_FORMAT_169("HHmmss"),
    TIME_FORMAT_170("HHssmm"),
    TIME_FORMAT_171("mmHHss"),
    TIME_FORMAT_172("mmssHH"),
    TIME_FORMAT_173("ssHHmm"),
    TIME_FORMAT_174("ssmmHH"),
    TIME_FORMAT_175("HH mm ss"),
    TIME_FORMAT_176("HH ss mm"),
    TIME_FORMAT_177("mm HH ss"),
    TIME_FORMAT_178("mm ss HH"),
    TIME_FORMAT_179("ss HH mm"),
    TIME_FORMAT_180("ss mm HH");
    private String value;

    GlobalTimeFormat(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }


    public static GlobalTimeFormat getKey(String type) {
        for (GlobalTimeFormat format : GlobalTimeFormat.values()) {
            if (type.equals(format.getValue()))
                return format;
        }
        return null;
    }
}
